/**
 *
 * $Id$
 */
package de.hub.rcore.example.el.validation;

import de.hub.rcore.example.el.ELExpression;
import de.hub.rcore.example.el.ELVariable;

/**
 * A sample validator interface for {@link de.hub.rcore.example.el.ELAssignment}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ELAssignmentValidator {
	boolean validate();

	boolean validateExpr(ELExpression value);
	boolean validateAssignee(ELVariable value);
}
