/**
 *
 * $Id$
 */
package de.hub.rcore.example.el.validation;


/**
 * A sample validator interface for {@link de.hub.rcore.example.el.ELBlockStarementKind}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ELBlockStarementKindValidator {
	boolean validate();

	boolean validateSyntax(String value);
	boolean validateBlocks(int value);
	boolean validateExpressions(int value);
}
