/**
 *
 * $Id$
 */
package de.hub.rcore.example.el.validation;

import de.hub.rcore.example.el.ELClass;

/**
 * A sample validator interface for {@link de.hub.rcore.example.el.ELTypedElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ELTypedElementValidator {
	boolean validate();

	boolean validateType(ELClass value);

	boolean validateArray(boolean value);
}
