/**
 * generated by Xtext
 */
package de.hub.randomemf.ui.contentassist;

import de.hub.randomemf.ui.contentassist.AbstractRandomEMFProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class RandomEMFProposalProvider extends AbstractRandomEMFProposalProvider {
}
