/*
* generated by Xtext
*/
package de.hub.randomemf;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class RandomEMFUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return de.hub.randomemf.ui.internal.RandomEMFActivator.getInstance().getInjector("de.hub.randomemf.RandomEMF");
	}
	
}
