/*
 * generated by Xtext
 */
package de.hub.randomemf.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import de.hub.randomemf.ui.internal.RandomEMFActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RandomEMFExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return RandomEMFActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return RandomEMFActivator.getInstance().getInjector(RandomEMFActivator.DE_HUB_RANDOMEMF_RANDOMEMF);
	}
	
}
