/*
* generated by Xtext
*/
package de.hub.randomemf.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import de.hub.randomemf.services.RandomEMFGrammarAccess;

public class RandomEMFParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private RandomEMFGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected de.hub.randomemf.parser.antlr.internal.InternalRandomEMFParser createParser(XtextTokenStream stream) {
		return new de.hub.randomemf.parser.antlr.internal.InternalRandomEMFParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Generator";
	}
	
	public RandomEMFGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(RandomEMFGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
