/*
* generated by Xtext
*/
package de.hub.randomemf.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class RandomEMFAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("de/hub/randomemf/parser/antlr/internal/InternalRandomEMF.tokens");
	}
}
