/**
 * generated by Xtext
 */
package de.hub.randomemf.ui.quickfix;

import org.eclipse.xtext.xbase.ui.quickfix.XbaseQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#quickfixes
 */
@SuppressWarnings("all")
public class RandomEMFQuickfixProvider extends XbaseQuickfixProvider {
}
