/*
 * generated by Xtext
 */
package de.hub.randomemf.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class RandomEMFUiModule extends de.hub.randomemf.ui.AbstractRandomEMFUiModule {
	public RandomEMFUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
