/*
 * generated by Xtext
 */
package de.hub.randomemf;

import org.eclipse.xtext.scoping.IGlobalScopeProvider;

import com.google.inject.name.Names;

import de.hub.randomemf.scoping.RcoreScopeProvider;
import de.hub.randomemf.scoping.TypesAndImportUriAwareGlobalScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RandomEMFRuntimeModule extends de.hub.randomemf.AbstractRandomEMFRuntimeModule {
	@Override
	public Class<? extends IGlobalScopeProvider> bindIGlobalScopeProvider() {
		return TypesAndImportUriAwareGlobalScopeProvider.class;
	}

	public void configureIScopeProviderDelegate(com.google.inject.Binder binder) {
		binder.bind(org.eclipse.xtext.scoping.IScopeProvider.class).annotatedWith(Names.named(org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider.NAMED_DELEGATE)).to(RcoreScopeProvider.class);
	}
	
}
