/**
 * generated by Xtext
 */
package de.hub.randomemf.validation;

import de.hub.randomemf.validation.AbstractRandomEMFValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class RandomEMFValidator extends AbstractRandomEMFValidator {
}
